name: numba-examples
channels:
  - defaults
  - numba

dependencies:
  - python=3.7
  - numba=0.47
  - numba-scipy=0.2
  - scipy
  - icc_rt
  - dask
  - progressbar2
  - colorama
  - tbb
  - matplotlib
  - imageio
  - pip
  - pip:
    - r2pipe
    - graphviz
